apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: my-v-app
spec:
  selector:
    matchLabels:
      app: my-v-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: my-v-app
    spec:
      containers:
      - name: my-v-app
        image: motany/motan-complete-pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
