apiVersion: v1
kind: Service
metadata:
  name: my-v-service
  labels:
    app: my-v-app
spec:
  selector:
    app: my-v-app
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
